version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_HOST=mysql
    depends_on:
      - mysql

  main:
    build:
      context: .
      dockerfile: Dockerfile.main
    restart: always
    env_file:
      - .env
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_HOST=mysql
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    restart: always
    environment:
      TZ: Asia/Bangkok
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_db
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      TZ: Asia/Bangkok
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
